* se agregan funciones para comprobar codigos de error al finalizar cada etapa

diff --git a/mygit b/mygit
--- a/mygit
+++ b/mygit
@@ -3,11 +3,41 @@
 # Licence: GPL-2
 LC_ALL=C
 
+function agregar() {
+	if [[ $? = 0 ]]; then
+		echo -e "\e[00;1;92mArchivos agregados correctamente.\e[00m"
+	else
+		echo -e "\e[00;1;92mError al agregar archivos.\e[00m"
+		exit 1
+	fi
+}
+
+function hacercommit() {
+	if [[ $? = 0 ]]; then
+		echo -e "\e[00;1;92mCommit realizado correctamente.\e[00m"
+	else
+		echo -e "\e[00;1;92mError al realizar commit.\e[00m"
+		exit 1
+	fi
+}
+
+function hacerpush() {
+	if [[ $? = 0 ]]; then
+		echo -e "\e[00;1;92mEnvio realizado correctamente.\e[00m"
+	else
+		echo -e "\e[00;1;92mError al realizar envio.\e[00m"
+		exit 1
+	fi
+}
+
 case "$1" in
 	up)
 		git add .
+		agregar
 		git commit -a
+		hacercommit
 		git push --all
+		hacerpush
 		echo -e "\e[00;1;92mFinalizado...\e[00m"
 		;;
 
@@ -16,8 +46,11 @@ case "$1" in
 			cd $i
 			echo -e "\e[00;1;92m$(pwd)\e[00m"
 			git add .
+			agregar
 			git commit -a -m $2
+			hacercommit
 			git push --all
+			hacerpush
 			cd ..
 		done
 		echo -e "\e[00;1;92mFinalizado...\e[00m"
@@ -26,8 +59,11 @@ case "$1" in
 	change)
 		git log --decorate > changelog
 		git add .
+		agregar
 		git commit -a -m "* changelog"
+		hacercommit
 		git push --all
+		hacerpush
 		echo -e "\e[00;1;92mFinalizado...\e[00m"
 		;;
 
@@ -37,8 +73,11 @@ case "$1" in
 			echo -e "\e[00;1;92m$(pwd)\e[00m"
 			git log --decorate > changelog
 			git add .
+			agregar
 			git commit -a -m "* changelog"
+			hacercommit
 			git push --all
+			hacerpush
 			cd ..
 		done
 		echo -e "\e[00;1;92mFinalizado...\e[00m"
@@ -52,8 +91,11 @@ case "$1" in
 
 	sup)
 		git add .
+		agregar
 		git commit -S -a
+		hacercommit
 		git push --all
+		hacerpush
 		echo -e "\e[00;1;92mFinalizado...\e[00m"
 		;;
 
@@ -62,8 +104,11 @@ case "$1" in
 			cd $i
 			echo -e "\e[00;1;92m$(pwd)\e[00m"
 			git add .
+			agregar
 			git commit -S -a -m $2
+			hacercommit
 			git push --all
+			hacerpush
 			cd ..
 		done
 		echo -e "\e[00;1;92mFinalizado...\e[00m"
@@ -72,8 +117,11 @@ case "$1" in
 	schange)
 		git log --decorate > changelog
 		git add .
+		agregar
 		git commit -S -a -m "* changelog"
+		hacercommit
 		git push --all
+		hacerpush
 		echo -e "\e[00;1;92mFinalizado...\e[00m"
 		;;
 
@@ -83,8 +131,11 @@ case "$1" in
 			echo -e "\e[00;1;92m$(pwd)\e[00m"
 			git log --decorate > changelog
 			git add .
+			agregar
 			git commit -S -a -m "* changelog"
+			hacercommit
 			git push --all
+			hacerpush
 			cd ..
 		done
 		echo -e "\e[00;1;92mFinalizado...\e[00m"
